# Generated by Django 2.2.2 on 2019-06-04 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='str_comment',
            new_name='review',
        ),
        migrations.RemoveField(
            model_name='user',
            name='int_score',
        ),
        migrations.RemoveField(
            model_name='user',
            name='int_userid',
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
