# Generated by Django 2.2.2 on 2019-06-04 10:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0002_auto_20190604_1018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Review',
        ),
    ]
